=== DeadneM/Just-Cause-2_mod/JC2MapViewer 0.3.4/SavedObjectInfo/SavedObjectInfo.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="itemlist" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <!-- uint32 as hex (e.g. ABCD4567) -->
  <xs:simpleType name='ID'>
    <xs:restriction base='xs:hexBinary'>
      <xs:length value='4' fixed='true'/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:element name="sublist">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="item" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="iid" type="ID" use="required" />
            <xs:attribute name="x" type="xs:float" use="required" />
            <xs:attribute name="y" type="xs:float" use="required" />
            <xs:attribute name="set" type="xs:boolean" />
            <!-- explicit name -->
            <xs:attribute name="itemname" type="xs:string" />
          	<xs:attribute name="icon" type="xs:string" />
          </xs:complexType>
        </xs:element>
        <xs:element ref="sublist" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
      <!-- implicit name -->
      <xs:attribute name="itemname" type="xs:string" />
      <xs:attribute name="oid" type="ID" />
      <!-- part of category path -->
      <xs:attribute name="name" type="xs:string" />
      <xs:attribute name="icon" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="itemlist">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="sublist" />
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== DeadneM/Just-Cause-2_mod/JC2MapViewer 0.3.4/SavedObjectInfo/TriggerSaveHandler.xml
<?xml version="1.0" encoding="utf-8"?>
<itemlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="SavedObjectInfo.xsd">
	<sublist icon="chaos_item" name="Chaos Items">
		<sublist name="SAM Sites" itemname="SAM Site" oid="F7A92C17">
			<item iid="0088D283" x="21812.965" y="17238.6379" />
			<item iid="0224229D" x="11547.717" y="24170.694" />
			<item iid="0352B6DF" x="21189.512" y="5819.69" />
			<item iid="05A22332" x="19629.78" y="12564.365" />
			<item iid="05A9E12A" x="26343.269" y="30520.02" />
			<item iid="063D8B0D" x="1525.98" y="13337.293" />
			<item iid="074CEDDB" x="22143.857" y="26663.31" />
			<item iid="076AB01A" x="19038.53" y="9076.284" />
			<item iid="08C68420" x="22470.67" y="23500.824" />
			<item iid="0A63BA3C" x="21168.656" y="5217.44" />
			<item iid="0C65DBF1" x="17267.7686" y="12099.713" />
			<item iid="0EAD52DE" x="19502.44" y="6310.02" />
			<item iid="1032BBE0" x="25899.722" y="3349.5" />
			<item iid="107C6710" x="21241.271" y="9309" />
			<item iid="108D6D02" x="11017.307" y="22152.205" />
			<item iid="124B9334" x="11003.654" y="8340.396" />
			<item iid="12DE2D37" x="15057.587" y="17135.7111" />
			<item iid="143EBC4D" x="28671.37" y="30510.61" />
			<item iid="16C58C8C" x="11549.935" y="24029.048" />
			<item iid="17F01205" x="9182.879" y="6680.437" />
			<item iid="18C51983" x="21820.845" y="17403.775" />
			<item iid="1B5F24C3" x="27962.15" y="6976.52" />
			<item iid="1DCFB8E2" x="11943.47" y="28241.85" />
			<item iid="1EADCCC3" x="19233.094" y="12857.208" />
			<item iid="2122E182" x="14463.74" y="26282.595" />
			<item iid="2598B93E" x="31886.23" y="12087.55" />
			<item iid="262BEF18" x="20717.325" y="20605.154" />
			<item iid="2737E151" x="13455.23" y="22868.338" />
			<item iid="274AC23C" x="13302.863" y="29214.82" />
			<item iid="2769345A" x="25643.197" y="17923.334" />
			<item iid="276E379B" x="30290.57" y="14199.396" />
			<item iid="2A082384" x="14415.359" y="17356.1267" />
			<item iid="2ABAAAEA" x="6990.845" y="22053.671" />
			<item iid="2D20C541" x="13687.441" y="22748.776" />
			<item iid="2E77E46A" x="20092.143" y="10898.646" />
			<item iid="32DBB1DC" x="16400.28616" y="10018.608" />
			<item iid="3744BF99" x="29827.92" y="24761.847" />
			<item iid="37A5F745" x="28779.41" y="28134.41" />
			<item iid="37FCFA18" x="21144.714" y="11642.226" />
			<item iid="3ABA7186" x="24127.768" y="24770.69" />
			<item iid="3C29E907" x="5843.9" y="24822.751" />
			<item iid="3CF8ABE3" x="11619.256" y="28363.17" />
			<item iid="3D7C48AD" x="13385.38" y="29081.54" />
			<item iid="405551CE" x="10031.268" y="28474.34" />
			<item iid="40E0B002" x="3961.87" y="20067.768" />
			<item iid="44192C96" x="21121.416" y="11671.253" />
			<item iid="444E2DF4" x="16003.9683" y="7542.458" />
			<item iid="44662A37" x="2104.5" y="29950.11" />
			<item iid="46C3A27F" x="2860.12" y="22753.273" />
			<item iid="48A96230" x="9748.937" y="28425.78" />
			<item iid="4C6E7370" x="31395.06" y="7321.761" />
			<item iid="4E1E6826" x="11138.952" y="22079.604" />
			<item iid="51C74461" x="3875.02" y="20179.679" />
			<item iid="51D5B055" x="24739.253" y="10481.267" />
			<item iid="53575C41" x="25440.147" y="18047.901" />
			<item iid="537BCF1E" x="26257.597" y="4724.85" />
			<item iid="5496370B" x="16254.3809" y="23502.363" />
			<item iid="56B54240" x="27861.48" y="29638.61" />
			<item iid="5A3E2572" x="29276.42" y="29293.06" />
			<item iid="5B97571F" x="5772.41" y="29628.7" />
			<item iid="5C3CB1B0" x="9304.567" y="6554.856" />
			<item iid="5D72FDB5" x="11724.225" y="5054.68" />
			<item iid="5DABA76A" x="10994.3" y="8205.991" />
			<item iid="5DCEF82D" x="17147.791" y="28071.93" />
			<item iid="5F07926E" x="14501.681" y="17637.459" />
			<item iid="5F180D38" x="11953.208" y="27940.03" />
			<item iid="5F4A268D" x="15901.3965" y="23449.995" />
			<item iid="5F99FF24" x="15074.91" y="17639.172" />
			<item iid="631DE558" x="12000.635" y="4811.56" />
			<item iid="6592E1B2" x="16928.4595" y="9374.25" />
			<item iid="66076D02" x="27612.44" y="17379.4468" />
			<item iid="67A3E4E6" x="13092.591" y="6768.05" />
			<item iid="68F94DCF" x="15858.8972" y="7458.74" />
			<item iid="699D44CC" x="12324.657" y="25294.71" />
			<item iid="69B661CC" x="5696.85" y="27426.34" />
			<item iid="69FA09C5" x="27700.01" y="29990.23" />
			<item iid="6B934E97" x="25994.07" y="6239.8" />
			<item iid="6D286379" x="22197.913" y="16331.94631" />
			<item iid="6E6384BE" x="5459.01" y="23776.505" />
			<item iid="7048CDB8" x="11835.433" y="4921.29" />
			<item iid="73488194" x="774.63" y="22499.474" />
			<item iid="74FED1BD" x="29771.23" y="2907.16" />
			<item iid="758996B5" x="26358.35" y="2205.17" />
			<item iid="76104F25" x="20669.574" y="5631.3" />
			<item iid="762C9CE4" x="19149.792" y="25925.033" />
			<item iid="79F998E7" x="8629.075" y="9302.388" />
			<item iid="7A2E16F0" x="30565.82" y="28925.38" />
			<item iid="7B337D37" x="28540.64" y="30432.86" />
			<item iid="7BA57BCF" x="14521.662" y="17134.7661" />
			<item iid="7C6E85AD" x="19037.671" y="12651.043" />
			<item iid="7FDE2298" x="14178.961" y="27861.46" />
			<item iid="80E45CB0" x="11209.175" y="5297.35" />
			<item iid="812F2F78" x="16467.36707" y="7353.934" />
			<item iid="8165B36B" x="15836.7334" y="12697.382" />
			<item iid="81E0FAEB" x="14161.431" y="27712.13" />
			<item iid="824F05C1" x="22188.684" y="26585.67" />
			<item iid="8506A1D5" x="16606.4707" y="10099.011" />
			<item iid="858258A5" x="8865.584" y="1331.96" />
			<item iid="8A18230A" x="30147.16" y="27050.57" />
			<item iid="8A288E4A" x="1467.16" y="13216.112" />
			<item iid="8B648687" x="8224.411" y="26816.82" />
			<item iid="8BCBE9D9" x="5318.03" y="23762.612" />
			<item iid="8DAE3A7A" x="25619.071" y="31466.78" />
			<item iid="8EBFEC56" x="11460.948" y="14998.827" />
			<item iid="8FE61313" x="28044.46" y="31271.26" />
			<item iid="9057E738" x="16967.872" y="8872.111" />
			<item iid="92B52F44" x="7443.402" y="19243.412" />
			<item iid="934831D3" x="27482.6" y="8755.603" />
			<item iid="9608F063" x="27594.1" y="29996.64" />
			<item iid="968C1C76" x="30275.32" y="14173.961" />
			<item iid="96C12DBC" x="7348.837" y="19348.892" />
			<item iid="9754D4E7" x="27509.93" y="17236.0005" />
			<item iid="9A7A6999" x="27974.93" y="7173.125" />
			<item iid="9AD61956" x="25555.33" y="18080.443" />
			<item iid="9CC21F3C" x="23291.859" y="12872.868" />
			<item iid="9EF66408" x="7807.956" y="18646.41" />
			<item iid="9FAE4ED1" x="15162.215" y="17358.0831" />
			<item iid="A2767BAF" x="21123.614" y="9446.135" />
			<item iid="A32C5016" x="24599.817" y="10484.959" />
			<item iid="A4AF5718" x="24662.404" y="18701.558" />
			<item iid="A4E67047" x="29160.79" y="29313.64" />
			<item iid="A6A8A1EA" x="13120.065" y="25294.087" />
			<item iid="A77D048F" x="28219.2" y="31500.34" />
			<item iid="AB2E035F" x="13150.284" y="6812.137" />
			<item iid="AC80330D" x="19371.174" y="14293.604" />
			<item iid="ACA15193" x="5582.15" y="27446.1" />
			<item iid="ACD47DBE" x="11661.298" y="28089.39" />
			<item iid="ADBED4DD" x="28849.3" y="27985.55" />
			<item iid="AE48E602" x="12898.291" y="25342.863" />
			<item iid="AE78DE4F" x="5859.43" y="27631.7" />
			<item iid="AEA9B4E4" x="6767.559" y="21977.273" />
			<item iid="AFA763EA" x="9012.419" y="27798.1" />
			<item iid="B06A1545" x="8762.634" y="9406.615" />
			<item iid="B2C75D8C" x="11570.39" y="1035.05" />
			<item iid="B477F250" x="1392.96" y="13386.358" />
			<item iid="B5CEB07D" x="25646.365" y="3502.44" />
			<item iid="B6403B10" x="16887.3108" y="9066.747" />
			<item iid="B8A2F9BD" x="12313.858" y="25153.459" />
			<item iid="BA2522D7" x="19097.788" y="26010.944" />
			<item iid="BBF8FD8E" x="28031.78" y="7047.818" />
			<item iid="BCEB371B" x="21034.688" y="11578.758" />
			<item iid="BF4CC72C" x="5528.68" y="23806.284" />
			<item iid="BFE88333" x="25477.504" y="31177.47" />
			<item iid="C08C7928" x="13333.679" y="29121.91" />
			<item iid="C1657B13" x="1126.31" y="23307.833" />
			<item iid="C19B71BE" x="8368.385" y="26787.37" />
			<item iid="C2DE403B" x="21745.736" y="17365.6267" />
			<item iid="C30DDD55" x="29216.51" y="29347.67" />
			<item iid="C347108F" x="6821.124" y="22010.811" />
			<item iid="C6B12611" x="17055.2063" y="9278.438" />
			<item iid="C85FE207" x="29457.33" y="21264.216" />
			<item iid="CA23E194" x="13162.125" y="11518.397" />
			<item iid="CCA68599" x="19053.632" y="15600.0856" />
			<item iid="CCFE9AC8" x="26209.973" y="30596" />
			<item iid="CDAE0812" x="16002.5215" y="12740.667" />
			<item iid="CDC129C9" x="28636.05" y="31449.21" />
			<item iid="CDE3BAE4" x="28926.93" y="28088.14" />
			<item iid="D04572DE" x="22072.252" y="26713.18" />
			<item iid="D0919233" x="30665.26" y="28773.23" />
			<item iid="D3D49754" x="23434.455" y="17328.6764" />
			<item iid="D3F7CDFE" x="25492.792" y="31503.51" />
			<item iid="D670EDFB" x="21780.211" y="23582.714" />
			<item iid="D7F82404" x="30134.66" y="26924.38" />
			<item iid="DF11943D" x="22033.596" y="26765.35" />
			<item iid="DF683591" x="20593.518" y="13503.085" />
			<item iid="E02B123D" x="30164.78" y="14165.89" />
			<item iid="E03DCEEC" x="13022.742" y="19308.797" />
			<item iid="E2911A11" x="5857.77" y="29590.19" />
			<item iid="E33689C2" x="19335.847" y="9035.624" />
			<item iid="E5059364" x="23179.064" y="17513.486" />
			<item iid="E7CAD7BB" x="20294.432" y="22466.855" />
			<item iid="EADE2239" x="21451.218" y="9482.229" />
			<item iid="EB3E285A" x="25976.754" y="4741.2" />
			<item iid="EC6B6A62" x="25325.88" y="31462.53" />
			<item iid="EF6BE60E" x="25557.348" y="31096.12" />
			<item iid="F043DC38" x="21121.914" y="11545.056" />
			<item iid="F279B99C" x="19085.329" y="25742.852" />
			<item iid="F397738C" x="12998.089" y="25072.888" />
			<item iid="F3DB557C" x="8940.679" y="27963.12" />
			<item iid="F3DFBCC5" x="2010.6" y="29855.85" />
